version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 14
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  secondary-artifacts:
    indexphotos:
      base-directory: index-photos
      files:
        - index.js
        - package.json
        - appspec.yml
    searchphotos:
      base-directory: search-photos
      files:
        - lambda_function.py
        - appspec.yml
