version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install --upgrade awscli
  
  pre_build:
    commands:
      - echo Installing Node.js dependencies...
      - cd index-photos
      - npm install
      - cd ..
      - echo Installing Python dependencies...
      - cd search-photos
      - cd ..
  
  build:
    commands:
      - echo Packaging Node.js Lambda...
      - cd index-photos
      - zip -r ../index-photos.zip .
      - cd ..
      - echo Packaging Python Lambda...
      - cd search-photos
      - zip -r ../search-photos.zip .
      - cd ..
  
  post_build:
    commands:
      - echo Updating Lambda functions...
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://index-photos.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://search-photos.zip

artifacts:
  files:
    - index-photos.zip
    - search-photos.zip
  discard-paths: yes